---
title: "Data manipulation with dplyr"
output: github_document
---

```{r}
echo = FALSE
library(tidyverse)
```

```{r}
options(tibble.print_min = 3)

litters_data = read_csv("./data/FAS_litters.csv",
  col_types = "ccddiiii")
litters_data = janitor::clean_names(litters_data)

pups_data = read_csv("./data/FAS_pups.csv",
  col_types = "ciiiii")
pups_data = janitor::clean_names(pups_data)

```

```{r}
# specify columns to keep by naming them
select(litters_data, group, litter_number, gd0_weight, pups_born_alive)

# specify range of columns to keep
select(litters_data, group:gd_of_birth)

# specify columns to remove
select(litters_data, -pups_survive)

#renaming variables and selecting
select(litters_data, GROUP = group, LiTtEr_NuMbEr = litter_number)

#just renaming
rename(litters_data, GROUP = group, LiTtEr_NuMbEr = litter_number)

select(litters_data, starts_with("gd"))
select(litters_data, litter_number, pups_survive, everything())

relocate(litters_data, litter_number, pups_survive)

#learning assessment
select(pups_data, litter_number, sex, pd_ears)
```

```{r}
filter(pups_data, sex == 1)
```

```{r}
mutate(litters_data, wt_gain = gd18_weight - gd0_weight,
  group = str_to_lower(group))
  
#learning assessment
mutate(pups_data, pivot_minus7 = pd_pivot - 7)
mutate(pups_data, pd_sum = pd_ears + pd_eyes + pd_pivot + pd_walk)
```

```{r}
head(arrange(litters_data, group, pups_born_alive), 10)
```

```{r}
litters_data_raw = read_csv("./data/FAS_litters.csv",
  col_types = "ccddiiii")
litters_data_clean_names = janitor::clean_names(litters_data_raw)
litters_data_selected_cols = select(litters_data_clean_names, -pups_survive)
litters_data_with_vars = 
  mutate(
    litters_data_selected_cols, 
    wt_gain = gd18_weight - gd0_weight,
    group = str_to_lower(group))
litters_data_with_vars_without_missing = 
  drop_na(litters_data_with_vars, wt_gain)
litters_data_with_vars_without_missing

litters_data_clean = 
  drop_na(
    mutate(
      select(
        janitor::clean_names(
          read_csv("./data/FAS_litters.csv", col_types = "ccddiiii")
          ), 
      -pups_survive
      ),
    wt_gain = gd18_weight - gd0_weight,
    group = str_to_lower(group)
    ),
  wt_gain
  )


litters_data = 
  read_csv("./data/FAS_litters.csv", col_types = "ccddiiii") %>%
  janitor::clean_names() %>%
  select(-pups_survive) %>%
  mutate(
    wt_gain = gd18_weight - gd0_weight,
    group = str_to_lower(group)) %>% 
  drop_na(wt_gain)


litters_data = 
  read_csv("./data/FAS_litters.csv", col_types = "ccddiiii") %>%
  janitor::clean_names(dat = .) %>%
  select(.data = ., -pups_survive) %>%
  mutate(.data = .,
    wt_gain = gd18_weight - gd0_weight,
    group = str_to_lower(group)) %>% 
  drop_na(data = ., wt_gain)

litters_data %>%
  lm(wt_gain ~ pups_born_alive, data = .) %>%
  broom::tidy()

# learning assessment
read_csv("./data/FAS_pups.csv", col_types = "ciiiii") %>%
  janitor::clean_names() %>% 
  filter(sex == 1) %>% 
  select(-pd_ears) %>% 
  mutate(pd_pivot_gt7 = pd_pivot > 7)
```

