---
title: "Data Import"
output: github_document
---

```{r}
echo = FALSE
library(tidyverse)
library(readxl)
library(haven)
```


## Data Import: CSVs
Let's import data using the 'readr' package

```{r}
litters_df = read_csv("data/FAS_litters.csv")
litters_df = janitor::clean_names(litters_df)

litters_df
head(litters_df)
tail(litters_df)
```
```{r, eval - FALSE}
```

```{r}
skimr::skim(litters_df)
```
'read_csv' options...

```{r, eval = FALSE}
read_csv("data/FAS_litters.csv", na = c("", "NA", 999, 88))
```
## Other file formats
we need to read in an excel spreadsheet...
```{r}
read_excel("data/mlb11.xlsx")
```
```{r, eval = FALSE}
View(mlb_df)
```

```{r}
lotr_word = 
  read_excel(
    "data/LotR_Words.xlsx",
    range = "B3:D6")

view(lotr_word)
```

 ## Still more formats... 
 
 read in a SAS dataset
```{r}
pulse_df = read_sas("data/public_pulse_data.sas7bdat")
```

## Data export

```{r}
write_csv(lotr_word, file = "data/lotr_words_df.csv")

```

## Why not base r??
 
```{r}
dont_do_this_df = read.csv("data_FAS_litters.csv")
```
 
 
